version: "2"
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  redisinsight:
    image: redislabs/redisinsight
    depends_on:
      - "redis"
    ports:
      - 8001:8001
# open localhost:8001 | add connection | enter "redis" as hostname