version: '3'
services:
  db:
    image: mongo
    container_name: app_db
    ports:
      - "27017:27017"
    volumes:
      - /dbMigration:/dbMigration
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    container_name: mongo-express
    restart: always
    links:
      - 'db:mongo'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: app_db:27017
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: root
    image: mongo-express 
 