# @host=http://localhost:4000
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzcwNTY3MjYsImlhdCI6MTY3NzA1NDkyNiwidXNlcklkIjoiNjNmNWNiYjU5MTdiNDU0YmY4ZWM5NmQ1IiwiYnVzaW5lc3NJZCI6bnVsbH0.OYrVvo_647oQdOuG32jBhveV6RgQaFOVR4XxT4Xt5Uo


@host=https://node-app-tau.vercel.app/

GET {{host}}/v1/test

###

POST {{host}}/v1/auth/login
Content-Type: application/json

{
    "email" :"dev@gmail.com",
    "password" : "123"
}

###

POST {{host}}/v1/auth/register
Content-Type: application/json

{
    "email" :"dev2@gmail.com",
    "password" : "123"
}


###
# get users
GET {{host}}/v1/users
Authorization: {{token}}

 
###
# POST products
POST {{host}}/v1/product
Content-Type: application/json
Authorization: {{token}}

{

    "productName" : "apple111",
    "price" : "2000"
}
 
###
# get products
GET {{host}}/v1/product
Authorization: {{token}}


###
# SEND MAIL
POST {{host}}/v1/mail
Content-Type: application/json
Authorization: {{token}}

{
    "email" : "hamzameh122@gmail.com",
    "mailBody" : "2000"
}
 