@host=http://localhost:4000
# @host=https://node-app-tau.vercel.app/
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTI1OTU4NzgsInVzZXJJZCI6IjY0OTFjMjI2MGRlOTIyOGNhNmQ0ODMwZSIsImJ1c2luZXNzSWQiOm51bGx9.osuiiO86H99njcrBgKCroOw9uo46Ok0EkKlnCZUJRPk



GET {{host}}/v1/test

###

POST {{host}}/v1/auth/login
Content-Type: application/json

{
    "email" :"dev@dev.co",
    "password" : "123123"
}

###

POST {{host}}/v1/auth/register
Content-Type: application/json

{
    "email" :"dev@dev.co",
    "password" : "123123"
}


###
# get users
GET {{host}}/v1/users
Authorization: {{token}}

 
###
# POST products
POST {{host}}/v1/product
Content-Type: application/json
Authorization: {{token}}

{
    "id": 2,
    "productName": "jackets",
    "imageUrl": "https://allensolly.abfrl.in/blog/wp-content/uploads/2022/07/Jacket.jpg",
    "price": 2222
}
 
###
# get products
GET {{host}}/v1/product
Authorization: {{token}}

### for a specific user
# get products
GET {{host}}/v1/product/protected
Authorization: {{token}}


###
# SEND MAIL
POST {{host}}/v1/mail
Content-Type: application/json
Authorization: {{token}}

{
    "email" : ["hamzameh122@gmail.com", "hamxa2266@gmail.com"],
    "email2" : "hamzameh122@gmail.com",
    "subject" : "test",
    "mailBody" : "Dear  <p>This is a testing mail </p>  <p>Checking content </p> <br>  <p>Please dont do this </p> <h2>lol </h2>"
}
 

###
# get emails
GET {{host}}/v1/mail/hamzameh122@gmail.com
 


###
# JSON endpoint
POST {{host}}/v1/json-store
Content-Type: application/json

{
    "dataId" : "123123",
    "jsonData" : "123123"
}
 
###
GET {{host}}/v1/json-store

###
# JSON
GET {{host}}/v1/json-store/64d9e328ba313bf2c7b336a6


###
DELETE {{host}}/v1/json-store

 
###
POST {{host}}/v1/redis/lol2
Content-Type: application/json
Authorization: {{token}}

{
    "test Data" : ["hamzameh122@gmail.com", "hamxa2266@gmail.com"]
}
 
###
GET {{host}}/v1/redis/lol

 

 





