@host=http://localhost:4000
# @host=https://node-app-tau.vercel.app/
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTI1OTU4NzgsInVzZXJJZCI6IjY0OTFjMjI2MGRlOTIyOGNhNmQ0ODMwZSIsImJ1c2luZXNzSWQiOm51bGx9.osuiiO86H99njcrBgKCroOw9uo46Ok0EkKlnCZUJRPk


###
# JSON endpoint
POST {{host}}/v1/2fa/verifyToken
Content-Type: application/json

{
    "token" : "061050"
}
 
###
GET {{host}}/v1/2fa/generateQRCode

 
###Delete QR images stored in cloudinary
###
DELETE {{host}}/v1/image/dev
