version: '3'
services:
  db:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    # command: sh /db/migrateData.sh
    # volumes:
    #   - /dbMigration:/dbMigration
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root

  migrator: ## this service will start and migrate data and then stop
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataMigration


  mongo-express:
    container_name: mongo-express
    restart: always
    links:
      - 'db:mongo'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB:27017
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: root
    image: mongo-express
    depends_on:
      - db
